Repository Mathieu-CTL/oxygencs-grp-1---eq-8-, pull requests merged in 2024-06, with the labels that each got.

#4 ADD - Ajout des variables d'env.
  src/main.py
Labels: Codage

#9 ADD - Post data to the DB
  src/main.py
Labels: Pull Request

#11 Merge dev branch to main
  src/main.py
Labels: Pull Request

#13 HOTFIX - Save Data to DB
  src/main.py
Labels: bug, Codage

#15 Creation image docker
  .dockerignore
  Dockerfile
  Pipfile
  Pipfile.lock
Labels: Pull Request

#17 created pipeline workflow
  .github/workflows/pipelineci.yml
  src/main.py
Labels: Pull Request
