Repository Mathieu-CTL/oxygencs-grp-1---eq-8-, pull requests merged in 2024-07, with the labels that each got.

#19 18 creations tests unitaires et integrations
  Pipfile
  src/main.py
  test/test.py
Labels: Pull Request

#21 Added pre-commit githooks to oxygen
  .dockerignore
  .github/ISSUE_TEMPLATE/test-creation-template.md
  .github/workflows/pipelineci.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  Dockerfile
  pytest.ini
  requirements.txt
  src/main.py
  test/test_main.py
Labels: Test, Pull Request, Linting

#23 Env variable update
  env_file.enc
  src/main.py
Labels: enhancement, Pull Request

#25 Update pipelineci.yml
  .github/workflows/pipelineci.yml
Labels: Pull Request

#27 Kubectl deployment for oxygencs
  .github/workflows/pipelineci.yml
  env_file.enc
  kubectl/configmap.yaml
  kubectl/deployment.yaml
  kubectl/ingress.yaml
  kubectl/pod.yaml
  kubectl/secret.yaml
  kubectl/service.yaml
  test/test_main.py
Labels: Pull Request
